### ISSUE TITLE
user cannot specify location of bios from command line

### ISSUE THREAD

**Issue by ezpuzz** [simias/psx-rs#2]
would be nice to specify the location of bios from command line (also helpful for testing different BIOS versions)

**Comment by simias** [comment]
Yeah I can't say I'm very user friendly at that point.

Note that I've tried a few different BIOSes and at that point some of them cause the emulator to stop before the logo is displayed because they use different GPU commands to draw the logo primitives.

**Comment by ezpuzz** [comment]
right, yes I'm trying to get running with 1001 on OS X.  sdl is failing to initialize the GL context probably due to Intel Iris Pro not supporting whatever hardcoded version or something.  I'll try to help where I can if I can get this running, but I'm new to Rust. :)

**Comment by simias** [comment]
Cool! let me know if I can help. I'm advertising OpenGL 3.3 in the shaders but I use a few extensions such as permanent mappings and the debug extension.
